---
title: "Week 10"
subtitle: "Attention and Transformers"
editor: visual
---

[Slides](/lecs/w09/lec09.html) & [Recordings](https://q.utoronto.ca/courses/443734)

Suggested papers:

-   [Neural Machine Translation by Jointly Learning to Align and Translate (Bahdanau et al., 2014)](https://arxiv.org/pdf/1409.0473)
-   [Show, Attend and Tell: Neural Image Caption Generation with Visual Attention (Xu et al., 2015)](https://arxiv.org/abs/1502.03044)
-   [Transformers: Attention Is All You Need (Vaswani et al., 2017)](https://papers.nips.cc/paper/2017/file/3f5ee243547dee91fbd053c1c4a845aa-Paper.pdf)
-   [BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding (Devlin et al., 2018)](https://arxiv.org/pdf/1810.04805.pdf)
-   [Model scaling: Scaling Laws for Neural Language Models (Kaplan et al., 2020)](https://arxiv.org/pdf/2001.08361.pdf)
-   [PixelRNN: Pixel Recurrent Neural Networks (van den Oord et al., 2016)](https://arxiv.org/abs/1601.06759)
-   [WaveNet: A Generative Model for Raw Audio (van den Oord et al., 2016)](https://arxiv.org/abs/1609.03499)
-   [PixelCNN: Conditional Image Generation with PixelCNN Decoders (van den Oord et al., 2016)](https://arxiv.org/abs/1606.05328)

Dive into Deep Learning ([d2l.ai](https://d2l.ai)) sections:

-   [11.1 Queries, Keys, and Values](https://d2l.ai/chapter_attention-mechanisms-and-transformers/queries-keys-values.html)
-   [11.3 Attention Scoring Functions](https://d2l.ai/chapter_attention-mechanisms-and-transformers/attention-scoring-functions.html)
-   [11.4 The Bahdanau Attention Mechanism](https://d2l.ai/chapter_attention-mechanisms-and-transformers/bahdanau-attention.html)
-   [11.5 Multi-Head Attention](https://d2l.ai/chapter_attention-mechanisms-and-transformers/multihead-attention.html)
-   [11.6 Self-Attention and Positional Encoding](https://d2l.ai/chapter_attention-mechanisms-and-transformers/self-attention-and-positional-encoding.html)
-   [11.7 The Transformer Architecture](https://d2l.ai/chapter_attention-mechanisms-and-transformers/transformer.html)
-   [11.9 Large-Scale Pretraining with Transformers](https://d2l.ai/chapter_attention-mechanisms-and-transformers/large-pretraining-transformers.html)
-   [15.8 Bidirectional Encoder Representations from Transformers (BERT)](https://d2l.ai/chapter_natural-language-processing-pretraining/bert.html)

Transformer video: <https://www.youtube.com/watch?v=XSSTuhyAmnI>

<https://nlp.seas.harvard.edu/2018/04/03/attention.html>

<http://peterbloem.nl/blog/transformers>

Last year's A3 (a seq2seq autoencoder) <http://modelai.gettysburg.edu/2021/headlines/>

[Optional exercises with solutions](/optional_exercises/w09/exercises_w09.html "Optional Exercises"){aria-label="Week 9 optional exercises"}

<br><br>